using System;
using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Reconcilr.Generator;

[Generator]
public sealed class ReconcileGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fields = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Reconcilr.ReconcileAttribute",
            static (node, _) => node is VariableDeclaratorSyntax,
            static (syntaxContext, _) => (IFieldSymbol)syntaxContext.TargetSymbol);

        context.RegisterSourceOutput(fields, static (productionContext, field) => GenerateFieldShadow(productionContext, field));
    }

    private static void GenerateFieldShadow(SourceProductionContext context, IFieldSymbol field)
    {
        if (field.ContainingType is null)
        {
            return;
        }

        var propertyName = PublicName(field.Name);
        if (field.Type is INamedTypeSymbol model)
        {
            Generate(context, model, propertyName + "Shadow", field.ContainingType.ContainingNamespace, true, field.ContainingType, field, propertyName);
        }
        else if (field.Type is ITypeParameterSymbol)
        {
            GenerateTypeParameterFieldShadow(context, field, propertyName);
        }
    }

    private static void GenerateTypeParameterFieldShadow(SourceProductionContext context, IFieldSymbol field, string propertyName)
    {
        var shadowName = propertyName + "Shadow";
        var modelName = Display(field.Type);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.ComponentModel;");
        source.AppendLine();

        if (!field.ContainingType!.ContainingNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ").Append(field.ContainingType.ContainingNamespace.ToDisplayString()).AppendLine(";");
            source.AppendLine();
        }

        source.Append("partial class ").Append(TypeDeclarationName(field.ContainingType)).AppendLine();
        AppendTypeParameterConstraints(source, field.ContainingType);
        source.AppendLine("{");
        source.AppendLine($$"""
                private {{shadowName}}? _{{char.ToLowerInvariant(propertyName[0])}}{{propertyName.Substring(1)}}Shadow;

                public {{shadowName}} {{propertyName}} => _{{char.ToLowerInvariant(propertyName[0])}}{{propertyName.Substring(1)}}Shadow ??= new {{shadowName}}({{field.Name}});

                internal void Set{{propertyName}}({{modelName}} value)
                    => {{propertyName}}.Reconcile({{field.Name}} = value);

                public sealed class {{shadowName}} : INotifyPropertyChanged
                {
                    private {{modelName}} _current;

                    public event PropertyChangedEventHandler? PropertyChanged;

                    public {{shadowName}}({{modelName}} initial) => _current = initial;

                    public void Reconcile({{modelName}} next)
                    {
                        if (global::System.Collections.Generic.EqualityComparer<{{modelName}}>.Default.Equals(_current, next))
                        {
                            return;
                        }

                        _current = next;
                        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
                    }
                }
            """);
        source.AppendLine("}");

        context.AddSource(shadowName + ".Reconcilr.g.cs", source.ToString());
    }

    private static void Generate(
        SourceProductionContext context,
        INamedTypeSymbol root,
        string? rootShadowName,
        INamespaceSymbol targetNamespace,
        bool preserveRootConstruction,
        INamedTypeSymbol? containingType,
        IFieldSymbol? rootField,
        string? propertyName)
    {
        var models = new List<INamedTypeSymbol>();
        CollectModels(context, root, models, new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default), preserveRootConstruction);
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated />");
        source.AppendLine("#nullable enable");
        source.AppendLine("using System;");
        source.AppendLine("using System.ComponentModel;");
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine();

        if (!targetNamespace.IsGlobalNamespace)
        {
            source.Append("namespace ").Append(targetNamespace.ToDisplayString()).AppendLine(";");
            source.AppendLine();
        }

        if (containingType is not null)
        {
            source.Append("partial class ").Append(TypeDeclarationName(containingType)).AppendLine();
            AppendTypeParameterConstraints(source, containingType);
            source.AppendLine("{");
            EmitFieldMembers(source, root, rootShadowName!, rootField!, propertyName!);
        }

        for (var index = 0; index < models.Count; index++)
        {
            EmitShadow(source, models[index], index == 0 ? rootShadowName : null);
        }

        if (containingType is not null)
        {
            source.AppendLine("}");
        }

        context.AddSource((rootShadowName ?? root.Name) + ".Reconcilr.g.cs", source.ToString());
    }

    private static void EmitFieldMembers(StringBuilder source, INamedTypeSymbol model, string shadowName, IFieldSymbol field, string propertyName)
    {
        var modelName = Display(model);
        var shadowFieldName = "_" + char.ToLowerInvariant(propertyName[0]) + propertyName.Substring(1) + "Shadow";
        source.AppendLine($$"""
                private {{shadowName}}? {{shadowFieldName}};

                public {{shadowName}} {{propertyName}} => {{shadowFieldName}} ??= new {{shadowName}}({{field.Name}});

                internal void Set{{propertyName}}({{modelName}} value)
                    => {{propertyName}}.Reconcile({{field.Name}} = value);

            """);
    }

    private static void CollectModels(SourceProductionContext context, INamedTypeSymbol model, List<INamedTypeSymbol> models, HashSet<INamedTypeSymbol> visited, bool preserveConstruction)
    {
        if (!preserveConstruction)
        {
            model = model.OriginalDefinition;
        }
        if (!visited.Add(model))
        {
            return;
        }

        models.Add(model);
        foreach (var property in Properties(model))
        {
            if (TryGetCollectionElement(property.Type, out var elementType))
            {
                if (TryGetShadowType(elementType, out var collectionChild))
                {
                    CollectModels(context, collectionChild, models, visited, false);
                }

                continue;
            }

            if (TryGetShadowType(property.Type, out var child))
            {
                CollectModels(context, child, models, visited, false);
            }
        }
    }

    private static void EmitShadow(StringBuilder source, INamedTypeSymbol model, string? shadowName)
    {
        var modelName = Display(model);
        var declaration = shadowName is null ? ShadowDeclaration(model) : shadowName;
        var constructorName = shadowName ?? ShadowName(model);
        source.AppendLine($$"""
            public sealed class {{declaration}} : INotifyPropertyChanged
            {
                private {{modelName}}? _previous;
                private {{modelName}}? _current;

                public event PropertyChangedEventHandler? PropertyChanged;

            """);

        foreach (var property in Properties(model))
        {
            if (TryGetCollectionElement(property.Type, out var elementType))
            {
                if (TryGetShadowType(elementType, out var collectionChild))
                {
                    source.AppendLine($$"""    public global::Reconcilr.ReconciledCollection<{{Display(elementType)}}, {{ShadowDisplay(collectionChild)}}> {{property.Name}} { get; }""");
                }
                else
                {
                    source.AppendLine($$"""    public global::Reconcilr.ReconciledCollection<{{Display(elementType)}}, {{Display(elementType)}}> {{property.Name}} { get; }""");
                }
            }
            else if (TryGetShadowType(property.Type, out var child))
            {
                source.AppendLine($$"""    public {{ShadowDisplay(child)}} {{property.Name}} { get; }""");
            }
            else
            {
                source.AppendLine($$"""    public {{Display(property.Type)}} {{property.Name}} => _current is null ? default! : _current.{{property.Name}};""");
            }
        }

        source.AppendLine($$"""

                public {{constructorName}}({{modelName}}? initial)
                {
                    _previous = initial;
                    _current = initial;
            """);
        foreach (var property in Properties(model))
        {
            if (TryGetCollectionElement(property.Type, out var elementType))
            {
                if (TryGetShadowType(elementType, out var collectionChild))
                {
                    source.AppendLine($$"""
                            {{property.Name}} = new global::Reconcilr.ReconciledCollection<{{Display(elementType)}}, {{ShadowDisplay(collectionChild)}}>(
                                initial is null ? global::System.Array.Empty<{{Display(elementType)}}>() : initial.{{property.Name}},
                                static item => new {{ShadowDisplay(collectionChild)}}(item),
                                static (previous, next) => !ReferenceEquals(previous, next),
                                static (shadow, previous, next) =>
                                {
                                    shadow.Reconcile(next);
                                    return true;
                                });
                        """);
                }
                else
                {
                    source.AppendLine($$"""
                            {{property.Name}} = new global::Reconcilr.ReconciledCollection<{{Display(elementType)}}, {{Display(elementType)}}>(
                                initial is null ? global::System.Array.Empty<{{Display(elementType)}}>() : initial.{{property.Name}},
                                static item => item,
                                static (previous, next) => !global::System.Collections.Generic.EqualityComparer<{{Display(elementType)}}>.Default.Equals(previous, next),
                                static (_, _, _) => false);
                        """);
                }
            }
            else if (TryGetShadowType(property.Type, out var child))
            {
                source.AppendLine($$"""        {{property.Name}} = new {{ShadowDisplay(child)}}(initial is null ? null : initial.{{property.Name}});""");
            }
        }
        source.AppendLine($$"""
                }

                public void Reconcile({{modelName}}? next)
                {
                    if (ReferenceEquals(_current, next))
                    {
                        return;
                    }

                    _current = next;
                    ReconcileCore(_previous);
                    _previous = _current;
                }

                internal void ReconcileCore({{modelName}}? previous)
                {
            """);
        foreach (var property in Properties(model))
        {
            if (TryGetCollectionElement(property.Type, out var elementType))
            {
                source.AppendLine($$"""
                        if (!ReferenceEquals(previous is null ? null : previous.{{property.Name}}, _current is null ? null : _current.{{property.Name}}))
                        {
                            {{property.Name}}.Reconcile(_current is null ? global::System.Array.Empty<{{Display(elementType)}}>() : _current.{{property.Name}});
                        }
                    """);
            }
            else if (TryGetShadowType(property.Type, out var child))
            {
                source.AppendLine($$"""
                        if (!ReferenceEquals(previous is null ? null : previous.{{property.Name}}, _current is null ? null : _current.{{property.Name}}))
                        {
                            {{property.Name}}.Reconcile(_current is null ? null : _current.{{property.Name}});
                        }
                    """);
            }
            else
            {
                source.AppendLine($$"""
                        if (!global::System.Collections.Generic.EqualityComparer<{{Display(property.Type)}}>.Default.Equals(previous is null ? default! : previous.{{property.Name}}, _current is null ? default! : _current.{{property.Name}}))
                        {
                            OnPropertyChanged(nameof({{property.Name}}));
                        }
                    """);
            }
        }
        source.AppendLine("""
                }

                private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
                    => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
            }

            """);
    }

    private static IEnumerable<IPropertySymbol> Properties(INamedTypeSymbol type) => type.GetMembers().OfType<IPropertySymbol>()
        .Where(property => !property.IsStatic && property.GetMethod is not null && property.DeclaredAccessibility == Accessibility.Public);

    private static bool TryGetShadowType(ITypeSymbol type, out INamedTypeSymbol shadowType)
    {
        if (type is INamedTypeSymbol named && named.TypeKind == TypeKind.Class && named.SpecialType != SpecialType.System_String)
        {
            shadowType = named;
            return true;
        }

        shadowType = null!;
        return false;
    }

    private static bool TryGetCollectionElement(ITypeSymbol type, out ITypeSymbol elementType)
    {
        if (type.SpecialType == SpecialType.System_String)
        {
            elementType = null!;
            return false;
        }

        if (type is IArrayTypeSymbol array)
        {
            elementType = array.ElementType;
            return true;
        }

        if (type is INamedTypeSymbol named)
        {
            var enumerable = named.AllInterfaces.Concat(new[] { named }).FirstOrDefault(candidate =>
                candidate.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T);
            if (enumerable is INamedTypeSymbol enumerableType)
            {
                elementType = enumerableType.TypeArguments[0];
                return true;
            }
        }

        elementType = null!;
        return false;
    }

    private static string ShadowName(INamedTypeSymbol type) => type.Name + "Shadow";

    private static string ShadowDeclaration(INamedTypeSymbol type) => ShadowName(type) + TypeParameterList(type.TypeParameters);

    private static string ShadowDisplay(INamedTypeSymbol type) => ShadowName(type) + TypeArgumentList(type.TypeArguments);

    private static string TypeParameterList(ImmutableArray<ITypeParameterSymbol> parameters) => parameters.Length == 0
        ? string.Empty
        : "<" + string.Join(", ", parameters.Select(parameter => parameter.Name)) + ">";

    private static string TypeArgumentList(ImmutableArray<ITypeSymbol> arguments) => arguments.Length == 0
        ? string.Empty
        : "<" + string.Join(", ", arguments.Select(Display)) + ">";

    private static string TypeDeclarationName(INamedTypeSymbol type) => type.Name + TypeParameterList(type.TypeParameters);

    private static void AppendTypeParameterConstraints(StringBuilder source, INamedTypeSymbol type)
    {
        foreach (var parameter in type.TypeParameters)
        {
            var constraints = new List<string>();
            if (parameter.HasUnmanagedTypeConstraint)
            {
                constraints.Add("unmanaged");
            }
            else if (parameter.HasValueTypeConstraint)
            {
                constraints.Add("struct");
            }
            else if (parameter.HasReferenceTypeConstraint)
            {
                constraints.Add(parameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated ? "class?" : "class");
            }
            else if (parameter.HasNotNullConstraint)
            {
                constraints.Add("notnull");
            }

            constraints.AddRange(parameter.ConstraintTypes.Select(Display));
            if (parameter.HasConstructorConstraint)
            {
                constraints.Add("new()");
            }

            if (constraints.Count > 0)
            {
                source.Append("    where ").Append(parameter.Name).Append(" : ").Append(string.Join(", ", constraints)).AppendLine();
            }
        }
    }

    private static string PublicName(string fieldName)
    {
        var name = fieldName.TrimStart('_');
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    private static string Display(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
}